name: CI Pipeline

on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  deploy:
    needs: example
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando la aplicación..."